name: snap
on:
  push:
    tags:
      - 'fortress/*'
    branches:
      - fortress
  pull_request:
    branches:
      - fortress
  workflow_dispatch:

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '[["self-hosted", "linux", "X64", "xlarge", "jammy"]]'
      snap-track: '${{ github.base_ref || github.ref_name }}'
      snap-test-script: |
        #!/bin/bash
        set -euxo pipefail

        gazebo.gz gazebo --version
